name: allpass
description: A password manage application.

version: 1.7.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 动画
  animations: ^2.0.7
#  # IOS图标
#  cupertino_icons: ^1.0.2
  # Toast通知
  fluttertoast: ^8.1.2
  # 数据库
  sqflite: ^2.2.2
  # 应用路径
  path_provider: ^2.0.11
  # 密码加密
  encrypt: ^5.0.1
  # 文件管理
  file_picker: ^5.2.4
  # 打开链接
  url_launcher: ^6.1.7
  # 状态管理
  provider: ^6.0.5
  # 路由管理
  fluro: ^2.0.4
  # 持久化
  shared_preferences: ^2.0.15
  # 依赖注入
  get_it: ^7.2.0
  # 生物识别
  local_auth: ^2.1.3
  # 屏幕尺寸管理
  flutter_screenutil: ^5.6.0
  # 汉字转拼音
  lpinyin: ^2.0.3
  # 网络请求
  dio: ^4.0.6
  # 设备信息
  device_info: ^2.0.3
  # 分享功能
  share: ^2.0.4
  # 密钥存储
  flutter_secure_storage: ^7.0.1
  # XML解析
  xml: ^5.4.0
  # 已安装App
  device_apps: ^2.2.0
  # Logger
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/import_step1.jpg
    - assets/images/import_step2.jpg
    - assets/images/import_step3.jpg
    - assets/images/import_step4.jpg
    - assets/images/import_step5.png

  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf
